USE [master]
GO

/****** Object:  Database [RESTAURANT DATABASE]    Script Date: 26-12-2021 20:54:20 ******/
CREATE DATABASE [RESTAURANT DATABASE] ON  PRIMARY 
( NAME = N'RESTAURANT DATABASE', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\RESTAURANT DATABASE.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RESTAURANT DATABASE_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\RESTAURANT DATABASE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RESTAURANT DATABASE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RESTAURANT DATABASE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET ARITHABORT OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET  MULTI_USER 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RESTAURANT DATABASE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RESTAURANT DATABASE] SET  READ_WRITE 
GO


